kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
  namespace: default
data:
  config.yml: |-
    admin:
      port: 9990
    storage:
      kind: io.l5d.inMemory
    namers:
      - kind: io.l5d.k8s
        experimental: true
        host: 127.0.0.1
        port: 8001
    interfaces:
      - kind: io.l5d.thriftNameInterpreter
        ip: 0.0.0.0
        port: 4100
      - kind: io.l5d.httpController
        ip: 0.0.0.0
        port: 4180
