kind: ReplicationController
apiVersion: v1
metadata:
  namespace: default
  name: namerd
spec:
  replicas: 1
  selector:
    app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst

      volumes:
        - name: namerd-config
          configMap:
            name: namerd-config

      containers:
        - name: namerd
          image: buoyantio/namerd:1.3.6
          args:
            - /io.buoyant/namerd/config/config.yml
          imagePullPolicy: Always

          ports:
            - name: sync
              containerPort: 4100
            - name: ctl
              containerPort: 4180

          volumeMounts:
            - name: "namerd-config"
              mountPath: "/io.buoyant/namerd/config"
              readOnly: true
        - name: kubectl
          image: buoyantio/kubectl:v1.8.5
          args:
          - "proxy"
          - "-p"
          - "8001"
          imagePullPolicy: Always
