version: '2'

services:
  web:
    build: .
    container_name: web
    ports: ["8080:8080"]
    command: web -gen-addr=linkerd:4142 -word-addr=linkerd:4142

  gen:
    build: .
    container_name: gen
    ports: ["8181:8181"]
    command: gen

  word:
    build: .
    container_name: word
    ports: ["8282:8282"]
    command: word

  linkerd:
    image: buoyantio/linkerd:1.3.6
    container_name: linkerd
    ports: ["4142:4142", "4141:4141", "9990:9990"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/linkerd.yml

  namerd:
    image: buoyantio/namerd:1.3.6
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/namerd.yml
