kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: default
data:
  config.yml: |-
    admin:
      port: 9990
    routers:
      - protocol: http
        label: client
        servers:
          - port: 4180
        interpreter:
          kind: io.l5d.namerd
          dst: /$/inet/namerd-sync.default.svc.cluster.local/4100
        timeoutMs: 1000
        responseClassifier:
          kind: io.l5d.retryableRead5XX

      - protocol: http
        label: server
        servers:
          - port: 4080
            ip: 0.0.0.0
        baseDtab: /http/1.1 => /$/inet/127.1/8080
