apiVersion: v1
kind: Service
metadata:
  name: l5d
spec:
  selector:
    app: l5d
  clusterIP: None
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
