---
kind: ReplicationController
apiVersion: v1
metadata:
  namespace: default
  name: gen

spec:
  replicas: 3
  selector:
    app: gen
  template:
    metadata:
      labels:
        app: gen

    spec:
      dnsPolicy: ClusterFirst
      volumes:
        - name: linkerd-config
          configMap:
            name: linkerd-config

      containers:
        - name: svc
          image: gobsvc/gob:0.8.6
          command:
            - gen
            - --srv=:8080
          ports:
            - name: http
              containerPort: 8080

        - name: l5d
          image: buoyantio/linkerd:1.3.6
          args:
            - "/io.buoyant/linkerd/config/config.yml"

          ports:
            - name: grpc-out
              containerPort: 4180
            - name: admin
              containerPort: 9990

          volumeMounts:
            - name: "linkerd-config"
              mountPath: "/io.buoyant/linkerd/config"
              readOnly: true
