version: '2'

services:

  app1_a:
    build: .

  app1_b:
    build: .
    command: -latency=1s -success-rate=0.8

  app2_a:
    build: .

  app2_b:
    build: .
    command: -latency=2s -success-rate=0.4

  # route 90% of traffic to app1, 10% to app2
  linkerd1:
    image: buoyantio/linkerd:1.3.6
    volumes:
    - ./linkerd1.yml:/io.buoyant/linkerd/config.yml:ro
    - ./disco:/disco:ro
    command:
    - "/io.buoyant/linkerd/config.yml"

  # route 25% of traffic to app1, 75% to app2
  linkerd2:
    image: buoyantio/linkerd:1.3.6
    volumes:
    - ./linkerd2.yml:/io.buoyant/linkerd/config.yml:ro
    - ./disco:/disco:ro
    command:
    - "/io.buoyant/linkerd/config.yml"

  influxdb:
    image: influxdb:1.2.2

  telegraf:
    image: telegraf:1.2.1
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:3.1.1
    ports:
    - 3000:3000
    volumes:
    - ./grafana.json:/usr/share/grafana/public/dashboards/home.json:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  grafana_bootstrap:
    image: buoyantio/slow_cooker:1.1.0
    entrypoint: /bin/sh
    volumes:
    - ./grafana-bootstrap.sh:/grafana-bootstrap.sh:ro
    command: >
      -c '/grafana-bootstrap.sh'

  # sends requests to linkerd1 at 100qps
  slow_cooker1:
    image: buoyantio/slow_cooker:1.1.0
    environment:
    - http_proxy=http://linkerd1:4140
    entrypoint: /bin/sh
    command: >
      -c 'sleep 15 && slow_cooker -qps 10 -concurrency 10 -interval 5s http://app/'

  # sends requests to linkerd2 at 200qps
  slow_cooker2:
    image: buoyantio/slow_cooker:1.1.0
    environment:
    - http_proxy=http://linkerd2:4140
    entrypoint: /bin/sh
    command: >
      -c 'sleep 15 && slow_cooker -qps 10 -concurrency 20 -interval 5s http://app/'
