# linkerd config for basic http proxy
# listens on port 4140, routes via http_proxy or host header
# expects marathon to be available on localhost

admin:
  ip: 0.0.0.0
  port: 9990

telemetry:
- kind: io.l5d.prometheus

usage:
  orgId: linkerd-examples-mesos-marathon

namers:
- kind: io.l5d.marathon
  host: localhost
  port: 8080

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  dtab: >- # route based on marathon name
    /marathonId => /#/io.l5d.marathon;
    /svc        => /$/io.buoyant.http.domainToPathPfx/marathonId;
  label: linkerd_proxy
